apiVersion: v1
kind: Service
metadata:
  name: lets-draw-together
  labels:
    app: lets-draw-together
spec:
  type: LoadBalancer
  ports:
  - port: 1234
    name: lets-draw-together
  selector:
    app: lets-draw-together
